In [3]:
import pandas as pd 

df = pd.read_csv("https://raw.githubusercontent.com/Esther-Velasco/esther_labs/main/W3/Mini%20project/Startups%20in%202021%20end.csv", on_bad_lines='skip')
df

HTTPError: HTTP Error 404: Not Found

In [4]:
df.columns

NameError: name 'df' is not defined

In [ ]:
df.nunique()

In [ ]:
df.Industry.value_counts()

In [ ]:
industry_mapping = {
    "Artificial intelligence":"Artificial intelligence",
    "Artificial Intelligence":"Artificial intelligence"                    
}

df['Industry']= list(map(lambda x:industry_mapping.get(x,x),df['Industry']))

In [7]:
df.columns = df.columns.str.replace(' ','_')

In [8]:
df.columns = df.columns.str.lower()

In [9]:
startups = df.drop(("select_investors"), axis = 1)
startups = df.drop(("unnamed:_0"), axis = 1)
startups

,company,valuation_($b),date_joined,country,city,industry,select_investors
0,Bytedance,$140,4/7/2017,China,Beijing,Artificial intelligence,"Sequoia Capital China, SIG Asia Investments, S..."
1,SpaceX,$100.3,12/1/2012,United States,Hawthorne,Other,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,Stripe,$95,1/23/2014,United States,San Francisco,Fintech,"Khosla Ventures, LowercaseCapital, capitalG"
3,Klarna,$45.6,12/12/2011,Sweden,Stockholm,Fintech,"Institutional Venture Partners, Sequoia Capita..."
4,Canva,$40,1/8/2018,Australia,Surry Hills,Internet software & services,"Sequoia Capital China, Blackbird Ventures, Mat..."
...,...,...,...,...,...,...,...
931,YipitData,$1,12/6/2021,United States,New York,Internet software & services,"RRE Ventures+, Highland Capital Partners, The ..."
932,Anyscale,$1,12/7/2021,United States,Berkeley,Artificial intelligence,"Andreessen Horowitz, Intel Capital, Foundation..."
933,Iodine Software,$1,12/1/2021,United States,Austin,Data management & analytics,"Advent International, Bain Capital Ventures, S..."
934,ReliaQuest,$1,12/1/2021,United States,Tampa,Cybersecurity,"KKR, FTV Capital, Ten Eleven Ventures"
935,Pet Circle,$1,12/7/2021,Australia,Alexandria,E-commerce & direct-to-consumer,"Prysm Capital, Baillie Gifford & Co., TDM Grow..."

In [10]:
startups.country.value_counts()

United States           477
China                   169
India                    51
United Kingdom           37
Germany                  23
Israel                   21
France                   19
Brazil                   15
Canada                   15
South Korea              11
Singapore                11
Hong Kong                 7
Japan                     6
Australia                 6
Netherlands               5
Mexico                    5
Switzerland               4
Sweden                    4
Indonesia                 4
Spain                     4
Norway                    3
Ireland                   3
United Arab Emirates      3
Turkey                    2
Colombia                  2
Belgium                   2
Austria                   2
Finland                   2
Denmark                   2
Philippines               2
Thailand                  2
South Africa              2
Luxembourg                1
Vietnam                   1
Estonia                   1
Lithuania                 1
Argentina                 1
Nigeria                   1
Santa Clara               1
Bermuda                   1
Senegal                   1
Chile                     1
Malaysia                  1
Czech Republic            1
Croatia                   1
United States,            1
Indonesia,                1
Name: country, dtype: int64

In [11]:
country_mapping = {
    "United States":"United States",
    "United States,":"United States",
    "Indonesia":"Indonesia",
    "Indonesia,":"Indonesia"
}

startups['country']= list(map(lambda x:country_mapping.get(x,x),startups['country']))

In [12]:
startups.country.unique()

array(['China', 'United States', 'Sweden', 'Australia', 'United Kingdom',
       'Brazil', 'Hong Kong', 'India', 'Indonesia', 'Germany', 'Mexico',
       'Canada', 'Turkey', 'South Korea', 'Netherlands', 'Israel',
       'Colombia', 'Belgium', 'Lithuania', 'Estonia', 'France', 'Austria',
       'Ireland', 'Singapore', 'Vietnam', 'United Arab Emirates',
       'Switzerland', 'Argentina', 'Spain', 'Japan', 'Luxembourg',
       'Nigeria', 'Santa Clara', 'Finland', 'Philippines', 'Denmark',
       'Senegal', 'Bermuda', 'Norway', 'South Africa', 'Chile',
       'Thailand', 'Malaysia', 'Czech Republic', 'Croatia'], dtype=object)

In [13]:
city_mapping = {
    "South San Francisco":"San Francisco",
    "Tel Aviv-Yafo,":"Tel Aviv",
    "Washington":"Washington DC",
}

startups['city']= list(map(lambda x:city_mapping.get(x,x),startups['city']))

In [14]:
startups

,company,valuation_($b),date_joined,country,city,industry,select_investors
0,Bytedance,$140,4/7/2017,China,Beijing,Artificial intelligence,"Sequoia Capital China, SIG Asia Investments, S..."
1,SpaceX,$100.3,12/1/2012,United States,Hawthorne,Other,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,Stripe,$95,1/23/2014,United States,San Francisco,Fintech,"Khosla Ventures, LowercaseCapital, capitalG"
3,Klarna,$45.6,12/12/2011,Sweden,Stockholm,Fintech,"Institutional Venture Partners, Sequoia Capita..."
4,Canva,$40,1/8/2018,Australia,Surry Hills,Internet software & services,"Sequoia Capital China, Blackbird Ventures, Mat..."
...,...,...,...,...,...,...,...
931,YipitData,$1,12/6/2021,United States,New York,Internet software & services,"RRE Ventures+, Highland Capital Partners, The ..."
932,Anyscale,$1,12/7/2021,United States,Berkeley,Artificial intelligence,"Andreessen Horowitz, Intel Capital, Foundation..."
933,Iodine Software,$1,12/1/2021,United States,Austin,Data management & analytics,"Advent International, Bain Capital Ventures, S..."
934,ReliaQuest,$1,12/1/2021,United States,Tampa,Cybersecurity,"KKR, FTV Capital, Ten Eleven Ventures"
935,Pet Circle,$1,12/7/2021,Australia,Alexandria,E-commerce & direct-to-consumer,"Prysm Capital, Baillie Gifford & Co., TDM Grow..."

In [15]:
df_clean = startups.drop(("select_investors"), axis = 1)

#we figured we needed to create the foreign key values data so we create index columns for city_id, 
#country_id, startup_id and industry_id

In [30]:

df_clean["country_id"]= range(1, len(df_clean) + 1)
df_clean["city_id"] = range(1, len(df_clean) + 1)
df_clean["startup_id"] = range(1, len(df_clean) + 1)
df_clean["industry_id"] = range(1, len(df_clean) + 1)
df_clean

,company,valuation_($b),date_joined,country,city,industry,country_id,city_id,startup_id,industry_id
0,Bytedance,$140,4/7/2017,China,Beijing,Artificial intelligence,1,1,1,1
1,SpaceX,$100.3,12/1/2012,United States,Hawthorne,Other,2,2,2,2
2,Stripe,$95,1/23/2014,United States,San Francisco,Fintech,3,3,3,3
3,Klarna,$45.6,12/12/2011,Sweden,Stockholm,Fintech,4,4,4,4
4,Canva,$40,1/8/2018,Australia,Surry Hills,Internet software & services,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...
931,YipitData,$1,12/6/2021,United States,New York,Internet software & services,932,932,932,932
932,Anyscale,$1,12/7/2021,United States,Berkeley,Artificial intelligence,933,933,933,933
933,Iodine Software,$1,12/1/2021,United States,Austin,Data management & analytics,934,934,934,934
934,ReliaQuest,$1,12/1/2021,United States,Tampa,Cybersecurity,935,935,935,935
935,Pet Circle,$1,12/7/2021,Australia,Alexandria,E-commerce & direct-to-consumer,936,936,936,936

In [32]:
# Specify the path where you want to save the CSV file
output_path = "https://github.com/Esther-Velasco/esther_labs/tree/main/W3/Mini%20project"

# Use the to_csv method to save the DataFrame to a CSV file
df_clean.to_csv("startups_index.csv", index=False)